### ISSUE TITLE
On-screen controls for GameScreen

### ISSUE THREAD

**Issue by kevinwinahradsky** [CSC-380/CSC380Game#18]
We will need some sort of on screen control mechanism for controlling the ball when the accelerometer is not available. Possible ideas are button controls or just touch sensitive quadrants on the screen.

**Comment by kevinwinahradsky** [comment]
In the last meeting for this we discussed just having touch zones on the screen. This way we would not have to have buttons that would obstruct the view or have to scale down the view to be able to show buttons. So just touching the top of the screen would simulate tilting forward, touching the bottom would simulate tilting back, etc...

**Comment by kmae26** [comment]
I was creating a dpad image that was see through, that when touched in proper places was like tilting in said direction, does everyone want me to change this

**Comment by kevinwinahradsky** [comment]
I will say its up to you since you are doing it :) I was just adding the comment from what was discussed in the last meeting. You could even do it both ways if you want and we can make it configurable as to which one is used or we could just see which one works best.
