### ISSUE TITLE
Tablet scaling issues

### ISSUE THREAD

**Issue by kevinwinahradsky** [CSC-380/CSC380Game#20]
On tablets the text in menu screens is very small. The game can also be distorted if the tablet does not have a 3:2 aspect ratio.

**Comment by dloom** [comment]
Its not scaling on my phone after the most recent dl from the master

**Comment by kevinwinahradsky** [comment]
Converted this back to a fixed screen size in 8ee4022cc15e4711394f3cf2cfd3416d2923a664

It will also correctly letter box the screen if the screen does not fit the aspect ratio of the screen. This way the game will always look exactly the same no matter what size the screen is.

**Comment by kmae26** [comment]
The way I had it perfectly scaled the screen stage to different screen sizes, it's the buttons that don't scale properly

**Comment by kevinwinahradsky** [comment]
What you had didnt scale the screen, It basically zoomed it. So on a large high resolution tablet the game would be zoomed out so you saw the whole game level at once with everything being rather small. I'm not sure that is something we really want.

**Comment by jdejong848** [comment]
No Kevin is right, it should scale to screens that way the view is the same
no matter what size

**Comment by kmae26** [comment]
To me, I thought that we need to get the screen size for the device you're running it on, then scale everything else using those numbers? Ignoring tables for the moment that's why they always have separate apps for phones/tables.

**Comment by kevinwinahradsky** [comment]
We could do it either way but here is how it kind of breaks down.

We have the current scaling method where it basically draws the rendered image as one fixed size and then scales up (or down) the rendered image to match the full screen size of the device. The drawbacks are that if the rendered image does not match the screens aspect ratio then we get the letter boxed black bars to compensate, like you do with an old tv show on a new hd tv. Another drawback is that if the rendered image is scaled up too much it can start to look pixelated. The pros are that we do not have to worry much about layout or calculating things, we just do it once and we are good to go. So it is pretty simple.

The other option would be to scale to different screen sizes and aspect ratios. The drawback to this is that we may need to do multiple versions of the same screens so that everything fits well at different sizes. We would also need multiple sets of assets for different screen sizes so that things line up well at different sizes and also look nice. So a 32x32 set, a 64x64 set, a 128x128 set, etc... So it really ends up being a lot more work. The pro is that it will all look much nicer in the end.

So the latter approach will give much nicer results in the end but will require a fair bit more work. A quality professional app will do things this way. I think for us though it is more work than we need for the end of the semester. 

Personally I would also rather spend any extra time adding in new features (Motion detecting rocket traps!) for the game rather than tweaking the views for different aspect ratios. :)

**Comment by jdejong848** [comment]
I still like the scaling option better purely for less work and I doubt
anyone would recognize it if we spent more time on screen aspect ratios but
if we spent more time on making the app enjoyable people would notice. Also
if the text boxes aren't large enough you can see if changing the value in
text button.font.scale to a value that appears suitable, I had it at 5
because it seemed reasonable to my tablet. My question is what happened to
the menus that made the scaling get screwed up? I though all the tweaking
we have done lately has been game related not menus

**Comment by kevinwinahradsky** [comment]
button.font.scale basically is a multiplier for the size. So setting it to 5 made it 5 times larger, for everyone. On a little phone the menus no longer fit on the screen. It worked on a tablet though because at the time the screen was being set to the native resolution. 

It's hard not to keep tweaking other parts as you go along :) I think Kelly and I were just messing with different ideas for the same thing.
