### ISSUE TITLE
More advanced map panning

### ISSUE THREAD

**Issue by kevinwinahradsky** [CSC-380/CSC380Game#21]
The camera needs to stop panning once it reaches the edge of the map so that we do not see the blank areas beyond the map. Some limited motion for the ball in the center of the map might be a nice affect as well.

**Comment by kevinwinahradsky** [comment]
did you finish this?

**Comment by kmae26** [comment]
Yes I did, just pushed it to Kelly, need to sync with the scoring Bo did then will push to master
