### ISSUE TITLE
Velocity not recording properly

### ISSUE THREAD

**Issue by kmae26** [CSC-380/CSC380Game#22]
At times the ball can get out of control and in attempts to stop this I've discovered that the Velocity on the ball body is not being recorded when tilting the screen, only when the ball hits a push bumper or static wall. if you allow the ball to rest in a corner of the map against a wall or two, the ball is not moving but the velocity of the ball is still changing.

**Comment by kevinwinahradsky** [comment]
Not sure what you mean by this. Are you seeing this on a phone, the emulator, and/or desktop? If you turn on the debug view in the settings the velocities will be shown on the screen. If the Tilt values are at 0 then the velocities on the ball will eventually degrade to 0. If you put the ball into a corner they go to 0 pretty quickly.

**Comment by kmae26** [comment]
I'm still using the desktop to test. My fault I put this up too soon before I figured more out. It's the angular velocity that isn't returning to normal while the ball is stationary I believe. Just having an issue with the ball getting crazy out of control, perhaps it's easier to control on a phone when you can actually tilt it rather than use keys, but if I'm having these problems that means using the dpad has these problems even if it's perfect otherwise.

**Comment by kevinwinahradsky** [comment]
Is this when it hits a bumper and then just keeps accelerating and gets stuck in this perpetual bounce between the bumper and a wall?

**Comment by kmae26** [comment]
The bumpers don't help at all lol  but can happen just by tilting in one direction for a long time
