### ISSUE TITLE
Settings do not load when the game starts

### ISSUE THREAD

**Issue by kevinwinahradsky** [CSC-380/CSC380Game#29]
Settings currently only load when the settings screen is loaded, They need to load when the game loads so that the rest of the app can make use of them.

**Comment by dloom** [comment]
oh i thought they did hmm ill work on that

**Comment by kevinwinahradsky** [comment]
This will be related to moving the properties calls into the Settings class. I think once that is figured out then that should solve this.

**Comment by dloom** [comment]
I switched it to settings and Im getting a null pointer exception at the creation of prefs i dont know why.

**Comment by kevinwinahradsky** [comment]
Can you send me what you did and the error message?

**Comment by kevinwinahradsky** [comment]
Or push it to a branch

**Comment by dloom** [comment]
ill push it to my branch im googling the prob right now
