### ISSUE TITLE
Implement the CreditScreen class

### ISSUE THREAD

**Issue by kevinwinahradsky** [CSC-380/CSC380Game#3]
Implement the CreditScreen class

**Comment by kevinwinahradsky** [comment]
This is the list of assets that have been kept track of so far. The list will need to be gone through and licenses for the various items will need to be checked to see how we have to add a credit for them.

**Comment by kevinwinahradsky** [comment]
https://github.com/CSC-380/CSC380Game/blob/master/CSC380GameProject-android/assets/data/asset-list.txt

**Comment by bguan2013** [comment]
Ok
